version: '3.8'

services:
  industrial-backend:
    command: python run.py
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1

  supply-backend:
    command: python run.py
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1

  park-backend:
    command: python run.py
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
